# Generated by Django 5.2.1 on 2025-07-29 19:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QACategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='QALanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Dil Kodu')),
                ('name', models.CharField(max_length=50, verbose_name='Dil Adı')),
            ],
            options={
                'verbose_name': 'Dil',
                'verbose_name_plural': 'Diller',
            },
        ),
        migrations.CreateModel(
            name='SoruCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant.qacategory', verbose_name='Kategori')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant.qalanguage', verbose_name='Dil')),
            ],
            options={
                'verbose_name': 'Soru-Cevap',
                'verbose_name_plural': 'Soru-Cevaplar',
            },
        ),
    ]
